name: Task 2 - NPM CI
on: [push, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Install and Test
        run: |
          if [ -f package.json ]; then
            npm install
            npm test
          else
            echo "No package.json found yet. Task skipped safely."
          fi